# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param synth.incrementalSynthesisCache C:/Users/Lenovo/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6008-DESKTOP-JK8LBQ7/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.cache/wt [current_project]
set_property parent.project_path C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Comparator_3bit.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Comparator_4bit.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Controller.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/D_FlipFlop.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Datapath.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/DownClocking_BaudRate.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Edge_to_Pulse.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/E7/E7.srcs/sources_1/new/MUX2x1.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/Reloadable_DownCounter.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/ShiftReg_10bit.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/StateMachine.sv
  C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/sources_1/new/CEP.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/constrs_1/new/cep.xdc
set_property used_in_implementation false [get_files C:/DriveA/Workspaces/Vivado/DSD_Lab/CEP/CEP.srcs/constrs_1/new/cep.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CEP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CEP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CEP_utilization_synth.rpt -pb CEP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
